# Generated by Django 2.1.5 on 2019-03-13 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applikaatio', '0003_auto_20190311_1802'),
    ]

    operations = [
        migrations.CreateModel(
            name='Arvostelu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arvosana', models.IntegerField()),
                ('kommentit', models.CharField(max_length=40)),
            ],
        ),
        migrations.DeleteModel(
            name='Koirapuisto',
        ),
    ]
